trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: GcpWifAuth@0
  inputs:
    connectedServiceId: 'gcp-federation' # Specify service connection to use
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'terraform init'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'terraform apply -auto-approve'
